deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access-key-id: $AWS_ACCESS_KEY_ID
  secret-access-key: $AWS_SECRET_KEY
  region: us-east-1
  app: $AWS_ELB_APP
  env: $AWS_ELB_ENV
  bucket_name: $AWS_ELB_BUCKET
  zip_file: './target//mpm-api-0.0.1-SNAPSHOT.jar'
sudo: false
branches:
  only:
  - master
language: java
script:
  - mvn clean install
notifications:
  email:
      on_failure: always
