deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access-key-id: $AWS_ACCESS_KEY_ID
  secret-access-key: $AWS_SECRET_KEY
  region: $AWS_REGION
  app: $AWS_ELB_APP
  env: $AWS_ELB_ENV
  bucket_name: $AWS_ELB_BUCKET
  zip_file: './target/mpm-api-1.0.2.jar'
sudo: false
branches:
  only:
  - master
language: java
script:
  - mvn clean install
notifications:
  email:
      on_failure: always
