info:
  name: @project.name@
  version: @project.version@
  description: @project.description@
  environment: ${MPMAPI_environment}
app:
  name: @project.name@
  version: @project.version@
  description: @project.description@
server.port: ${MPMAPI_port}
spring:
  datasource:
    url: jdbc:mysql://${MPMAPI_dbhost}/pympm?useSSL=false
    username: ${MPMAPI_dbuser}
    password: ${MPMAPI_dbpass}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.format_sql: false
logging:
  pattern.console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate: ERROR

security.basic.enable: false

mpm_api:
  apps:
    mpmjadmin:
      client_id: ${MPMAPI_mpmjadmin_client_id}
      client_secret: ${MPMAPI_mpmjadmin_client_secret}
      grant_type: ${MPMAPI_mpmjadmin_grant_type}
      role: ${MPMAPI_mpmjadmin_role}
    mpmMobile:
      client_id: ${MPMAPI_mpmMobile_client_id}
      client_secret: ${MPMAPI_mpmMobile_client_secret}
      grant_type: ${MPMAPI_mpmMobile_grant_type}
      role: ${MPMAPI_mpmMobile_role}
  cache:
    url:
      all: ${MPMAPI_cache_url_all}
      one: ${MPMAPI_cache_url_one}
    token:
      key: ${MPMAPI_cache_token_key}
      value: ${MPMAPI_cache_token_value}
  aws:
    client_id: ${MPMAPI_aws_client_id}
    client_secret: ${MPMAPI_aws_client_secret}
    s3:
      cc:
        static_bucket: ${MPMAPI_aws_s3_cc_static_bucket}
        bucket: ${MPMAPI_aws_s3_cc_bucket}
      mpm:
        static_bucket: ${MPMAPI_aws_s3_mpm_static_bucket}
        bucket: ${MPMAPI_aws_s3_mpm_bucket}
