
server.port: 80
spring:
  h2.console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:mysql://localhost/pympm?useSSL=false
    username: pympm
    password: pympm
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.format_sql: false
logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.security: DEBUG
    org.springframework.cloud: WARN
